"""initial migration

Revision ID: 9b6189514dd3
Revises: 
Create Date: 2026-08-07 11:52:15.391308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9b6189514dd3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('tier', sa.String(length=50), nullable=False),
    sa.Column('razorpay_sub_id', sa.String(length=100), nullable=True),
    sa.Column('monthly_quota', sa.Integer(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('passports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clerk_user_id', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clerk_user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('last_used_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('revoked_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_table('org_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('clerk_user_id', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'clerk_user_id', name='uq_org_member')
    )
    op.create_table('templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('html_source', sa.Text(), nullable=False),
    sa.Column('variables', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usage_ledger',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('credentials_issued', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('org_id', 'period')
    )
    op.create_table('webhook_endpoints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('secret', sa.String(length=255), nullable=False),
    sa.Column('events', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('credential_batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('csv_filename', sa.String(length=255), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('succeeded', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_report', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_batches_org_status', 'credential_batches', ['org_id', 'status'], unique=False)
    op.create_table('credentials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('public_id', sa.String(length=50), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=True),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('recipient_name', sa.String(length=255), nullable=False),
    sa.Column('recipient_email', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('pdf_url', sa.Text(), nullable=True),
    sa.Column('hmac_signature', sa.String(length=64), nullable=False),
    sa.Column('legacy_token', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('claimed_by_user_id', sa.String(length=255), nullable=True),
    sa.Column('issued_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('claimed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('revoked_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['credential_batches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_index('idx_credentials_legacy_token', 'credentials', ['legacy_token'], unique=False, postgresql_where='legacy_token IS NOT NULL')
    op.create_index('idx_credentials_org', 'credentials', ['org_id'], unique=False)
    op.create_index('idx_credentials_public_id', 'credentials', ['public_id'], unique=False)
    op.create_index('idx_credentials_recipient_email', 'credentials', ['recipient_email'], unique=False)
    op.create_table('passport_credentials',
    sa.Column('passport_id', sa.UUID(), nullable=False),
    sa.Column('credential_id', sa.UUID(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['credential_id'], ['credentials.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['passport_id'], ['passports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('passport_id', 'credential_id')
    )
    op.drop_table('courses')
    op.drop_index(op.f('idx_certificates_course'), table_name='certificates')
    op.drop_index(op.f('idx_certificates_issued_at'), table_name='certificates')
    op.drop_table('certificates')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('certificate_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('token_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('participant_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('course_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('completion_date', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('instructor_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('issued_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('revoked', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('revoked_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('client_ip', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('participant_email', sa.VARCHAR(length=255), server_default=sa.text("''::character varying"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('certificates_pkey')),
    sa.UniqueConstraint('token_hash', name=op.f('certificates_token_hash_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_certificates_issued_at'), 'certificates', [sa.literal_column('issued_at DESC')], unique=False)
    op.create_index(op.f('idx_certificates_course'), 'certificates', ['course_name'], unique=False)
    op.create_table('courses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('courses_pkey')),
    sa.UniqueConstraint('name', name=op.f('courses_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('passport_credentials')
    op.drop_index('idx_credentials_recipient_email', table_name='credentials')
    op.drop_index('idx_credentials_public_id', table_name='credentials')
    op.drop_index('idx_credentials_org', table_name='credentials')
    op.drop_index('idx_credentials_legacy_token', table_name='credentials', postgresql_where='legacy_token IS NOT NULL')
    op.drop_table('credentials')
    op.drop_index('idx_batches_org_status', table_name='credential_batches')
    op.drop_table('credential_batches')
    op.drop_table('webhook_endpoints')
    op.drop_table('usage_ledger')
    op.drop_table('templates')
    op.drop_table('org_members')
    op.drop_table('api_keys')
    op.drop_table('passports')
    op.drop_table('organizations')
    # ### end Alembic commands ###
